-- Idempotent schema patch script. Keep this file updated as the EF model evolves.

CREATE TABLE IF NOT EXISTS institutions (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(120) NOT NULL,
    "Type" character varying(20) NOT NULL,
    "IsActive" boolean NOT NULL DEFAULT TRUE,
    CONSTRAINT "PK_institutions" PRIMARY KEY ("Id")
);

CREATE UNIQUE INDEX IF NOT EXISTS "IX_institutions_Name_Type"
    ON institutions ("Name", "Type");

CREATE TABLE IF NOT EXISTS accounts (
    "Id" uuid NOT NULL,
    "UserId" uuid NOT NULL,
    "Name" character varying(120) NOT NULL,
    "Type" text NOT NULL,
    "InitialBalance" numeric(14,2) NOT NULL DEFAULT 0,
    "IsActive" boolean NOT NULL DEFAULT TRUE,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_accounts" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_accounts_users_UserId" FOREIGN KEY ("UserId") REFERENCES users ("Id") ON DELETE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS "IX_accounts_UserId_Name"
    ON accounts ("UserId", "Name");

CREATE INDEX IF NOT EXISTS "IX_accounts_UserId_IsActive"
    ON accounts ("UserId", "IsActive");

CREATE TABLE IF NOT EXISTS account_transactions (
    "Id" uuid NOT NULL,
    "AccountId" uuid NOT NULL,
    "UserId" uuid NOT NULL,
    "OccurredAt" timestamp with time zone NOT NULL,
    "Kind" text NOT NULL,
    "Amount" numeric(14,2) NOT NULL,
    "Description" character varying(200) NOT NULL,
    "SourceType" character varying(60),
    "SourceId" uuid,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_account_transactions" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_account_transactions_accounts_AccountId" FOREIGN KEY ("AccountId") REFERENCES accounts ("Id") ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS "IX_account_transactions_AccountId_OccurredAt"
    ON account_transactions ("AccountId", "OccurredAt");

CREATE INDEX IF NOT EXISTS "IX_account_transactions_UserId_OccurredAt"
    ON account_transactions ("UserId", "OccurredAt");

CREATE INDEX IF NOT EXISTS "IX_account_transactions_SourceType_SourceId"
    ON account_transactions ("SourceType", "SourceId");

CREATE TABLE IF NOT EXISTS user_notifications (
    "Id" uuid NOT NULL,
    "UserId" uuid NOT NULL,
    "PlanId" uuid NULL,
    "InstallmentId" uuid NULL,
    "MoneyType" text NULL,
    "Kind" text NOT NULL,
    "ReferenceKey" character varying(160) NOT NULL,
    "Title" character varying(160) NOT NULL,
    "Message" character varying(500) NOT NULL,
    "DueDate" date NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "ReadAt" timestamp with time zone NULL,
    CONSTRAINT "PK_user_notifications" PRIMARY KEY ("Id")
);

CREATE INDEX IF NOT EXISTS "IX_user_notifications_UserId_CreatedAt"
    ON user_notifications ("UserId", "CreatedAt");

CREATE UNIQUE INDEX IF NOT EXISTS "IX_user_notifications_UserId_ReferenceKey"
    ON user_notifications ("UserId", "ReferenceKey");

CREATE TABLE IF NOT EXISTS robot_execution_logs (
    "Id" uuid NOT NULL,
    "RobotName" character varying(80) NOT NULL,
    "StartedAt" timestamp with time zone NOT NULL,
    "FinishedAt" timestamp with time zone NOT NULL,
    "DurationMs" bigint NOT NULL DEFAULT 0,
    "CorrelationId" character varying(64) NOT NULL DEFAULT '',
    "HostName" character varying(120) NOT NULL DEFAULT 'unknown',
    "TriggeredByUserId" uuid NULL,
    "Success" boolean NOT NULL,
    "ProcessedCount" integer NOT NULL,
    "EmailsAttempted" integer NOT NULL DEFAULT 0,
    "EmailsSent" integer NOT NULL DEFAULT 0,
    "EmailsFailed" integer NOT NULL DEFAULT 0,
    "ZeroItemsReasonCode" character varying(100) NULL,
    "WasSkipped" boolean NOT NULL DEFAULT FALSE,
    "SkipReason" character varying(200) NULL,
    "Error" character varying(2000) NULL,
    CONSTRAINT "PK_robot_execution_logs" PRIMARY KEY ("Id")
);

CREATE INDEX IF NOT EXISTS "IX_robot_execution_logs_RobotName_StartedAt"
    ON robot_execution_logs ("RobotName", "StartedAt");

CREATE TABLE IF NOT EXISTS notification_settings (
    "Id" uuid NOT NULL,
    "IncomeUpcomingEnabled" boolean NOT NULL DEFAULT TRUE,
    "IncomeDaysBefore" integer NOT NULL DEFAULT 2,
    "ExpenseUpcomingEnabled" boolean NOT NULL DEFAULT TRUE,
    "ExpenseDaysBefore" integer NOT NULL DEFAULT 2,
    "ExpenseOverdueEnabled" boolean NOT NULL DEFAULT TRUE,
    "CardCloseSoonEnabled" boolean NOT NULL DEFAULT TRUE,
    "CardCloseDaysBefore" integer NOT NULL DEFAULT 2,
    "CardCloseDayEnabled" boolean NOT NULL DEFAULT TRUE,
    "MonthCloseEnabled" boolean NOT NULL DEFAULT TRUE,
    "MonthSummaryEnabled" boolean NOT NULL DEFAULT TRUE,
    "GoalBelowExpectedEnabled" boolean NOT NULL DEFAULT TRUE,
    "GoalCompletedEnabled" boolean NOT NULL DEFAULT TRUE,
    "GoalInactivityEnabled" boolean NOT NULL DEFAULT TRUE,
    "GoalInactivityDays" integer NOT NULL DEFAULT 30,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT NOW(),
    "UpdatedAt" timestamp with time zone NOT NULL DEFAULT NOW(),
    CONSTRAINT "PK_notification_settings" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS robot_settings (
    "Id" uuid NOT NULL,
    "Enabled" boolean NOT NULL DEFAULT TRUE,
    "DailyRunTimeUtc" character varying(5) NOT NULL DEFAULT '08:00',
    "UpdatedAt" timestamp with time zone NOT NULL DEFAULT NOW(),
    CONSTRAINT "PK_robot_settings" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS investment_allocation_targets (
    "Id" uuid NOT NULL,
    "UserId" uuid NOT NULL,
    "Rf" numeric(5,2) NOT NULL,
    "Acoes" numeric(5,2) NOT NULL,
    "Fundos" numeric(5,2) NOT NULL,
    "Cripto" numeric(5,2) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_investment_allocation_targets" PRIMARY KEY ("Id")
);

CREATE UNIQUE INDEX IF NOT EXISTS "IX_investment_allocation_targets_UserId"
    ON investment_allocation_targets ("UserId");

CREATE TABLE IF NOT EXISTS password_reset_tokens (
    "Id" uuid NOT NULL,
    "UserId" uuid NOT NULL,
    "TokenHash" character varying(200) NOT NULL,
    "ExpiresAt" timestamp with time zone NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UsedAt" timestamp with time zone NULL,
    CONSTRAINT "PK_password_reset_tokens" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_password_reset_tokens_users_UserId" FOREIGN KEY ("UserId") REFERENCES users ("Id") ON DELETE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS "IX_password_reset_tokens_TokenHash"
    ON password_reset_tokens ("TokenHash");

CREATE INDEX IF NOT EXISTS "IX_password_reset_tokens_UserId"
    ON password_reset_tokens ("UserId");

DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM information_schema.tables
        WHERE table_schema = 'public' AND table_name = 'robot_execution_logs'
    ) THEN
        ALTER TABLE robot_execution_logs ADD COLUMN IF NOT EXISTS "EmailsAttempted" integer NOT NULL DEFAULT 0;
        ALTER TABLE robot_execution_logs ADD COLUMN IF NOT EXISTS "EmailsSent" integer NOT NULL DEFAULT 0;
        ALTER TABLE robot_execution_logs ADD COLUMN IF NOT EXISTS "EmailsFailed" integer NOT NULL DEFAULT 0;
        ALTER TABLE robot_execution_logs ADD COLUMN IF NOT EXISTS "ZeroItemsReasonCode" character varying(100);
        ALTER TABLE robot_execution_logs ADD COLUMN IF NOT EXISTS "DurationMs" bigint NOT NULL DEFAULT 0;
        ALTER TABLE robot_execution_logs ADD COLUMN IF NOT EXISTS "CorrelationId" character varying(64) NOT NULL DEFAULT '';
        ALTER TABLE robot_execution_logs ADD COLUMN IF NOT EXISTS "HostName" character varying(120) NOT NULL DEFAULT 'unknown';
        ALTER TABLE robot_execution_logs ADD COLUMN IF NOT EXISTS "TriggeredByUserId" uuid;
        ALTER TABLE robot_execution_logs ADD COLUMN IF NOT EXISTS "WasSkipped" boolean NOT NULL DEFAULT FALSE;
        ALTER TABLE robot_execution_logs ADD COLUMN IF NOT EXISTS "SkipReason" character varying(200);
    END IF;

    IF EXISTS (
        SELECT 1
        FROM information_schema.tables
        WHERE table_schema = 'public' AND table_name = 'robot_settings'
    ) THEN
        ALTER TABLE robot_settings ADD COLUMN IF NOT EXISTS "Enabled" boolean NOT NULL DEFAULT TRUE;
        ALTER TABLE robot_settings ADD COLUMN IF NOT EXISTS "DailyRunTimeUtc" character varying(5) NOT NULL DEFAULT '08:00';
        ALTER TABLE robot_settings ADD COLUMN IF NOT EXISTS "UpdatedAt" timestamp with time zone NOT NULL DEFAULT NOW();
    END IF;

    IF EXISTS (
        SELECT 1
        FROM information_schema.tables
        WHERE table_schema = 'public' AND table_name = 'money_installments'
    ) THEN
        ALTER TABLE money_installments ADD COLUMN IF NOT EXISTS "StatementYear" integer;
        ALTER TABLE money_installments ADD COLUMN IF NOT EXISTS "StatementMonth" integer;
        ALTER TABLE money_installments ADD COLUMN IF NOT EXISTS "StatementCloseDate" date;
        ALTER TABLE money_installments ADD COLUMN IF NOT EXISTS "StatementDueDate" date;
    END IF;

    IF EXISTS (
        SELECT 1
        FROM information_schema.tables
        WHERE table_schema = 'public' AND table_name = 'money_payments'
    ) THEN
        ALTER TABLE money_payments ADD COLUMN IF NOT EXISTS "AccountId" uuid;

        IF NOT EXISTS (
            SELECT 1
            FROM pg_constraint
            WHERE conname = 'FK_money_payments_accounts_AccountId'
        ) THEN
            ALTER TABLE money_payments
            ADD CONSTRAINT "FK_money_payments_accounts_AccountId"
            FOREIGN KEY ("AccountId") REFERENCES accounts ("Id") ON DELETE SET NULL;
        END IF;
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS "IX_money_payments_AccountId"
    ON money_payments ("AccountId");

DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM information_schema.tables
        WHERE table_schema = 'public' AND table_name = 'user_profiles'
    ) THEN
        ALTER TABLE user_profiles ADD COLUMN IF NOT EXISTS "NotifyUpcomingEnabled" boolean NOT NULL DEFAULT TRUE;
        ALTER TABLE user_profiles ADD COLUMN IF NOT EXISTS "NotifyOverdueEnabled" boolean NOT NULL DEFAULT TRUE;
        ALTER TABLE user_profiles ADD COLUMN IF NOT EXISTS "NotifyEmailEnabled" boolean NOT NULL DEFAULT FALSE;
        ALTER TABLE user_profiles ADD COLUMN IF NOT EXISTS "NotifyInAppEnabled" boolean NOT NULL DEFAULT TRUE;
        ALTER TABLE user_profiles ADD COLUMN IF NOT EXISTS "NotifyDaysBeforeDue" integer NOT NULL DEFAULT 3;
    END IF;
END $$;

DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM information_schema.tables
        WHERE table_schema = 'public' AND table_name = 'users'
    ) THEN
        ALTER TABLE users ADD COLUMN IF NOT EXISTS "Role" character varying(30) NOT NULL DEFAULT 'Basic';
    END IF;
END $$;
