CREATE TABLE card_brands (
    "Id" integer NOT NULL,
    "Name" character varying(100) NOT NULL,
    "Code" character varying(50) NOT NULL,
    "IsActive" boolean NOT NULL,
    CONSTRAINT "PK_card_brands" PRIMARY KEY ("Id")
);

CREATE TABLE categories (
    "Id" uuid NOT NULL,
    "UserId" uuid,
    "Name" character varying(60) NOT NULL,
    "AppliesTo" text,
    "IsActive" boolean NOT NULL DEFAULT TRUE,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_categories" PRIMARY KEY ("Id")
);

CREATE TABLE goal_contributions (
    "Id" uuid NOT NULL,
    "GoalId" uuid NOT NULL,
    "UserId" uuid NOT NULL,
    "Amount" numeric(14,2) NOT NULL,
    "Date" date NOT NULL,
    "Note" character varying(300),
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_goal_contributions" PRIMARY KEY ("Id")
);

CREATE TABLE goals (
    "Id" uuid NOT NULL,
    "UserId" uuid NOT NULL,
    "Title" character varying(200) NOT NULL,
    "TargetAmount" numeric(14,2) NOT NULL,
    "CurrentAmount" numeric(14,2) NOT NULL DEFAULT 0.0,
    "Year" integer NOT NULL,
    "ExpectedMonthly" numeric(14,2) NOT NULL DEFAULT 0.0,
    "TargetDate" date,
    "Description" character varying(1000),
    "Status" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_goals" PRIMARY KEY ("Id")
);

CREATE TABLE institutions (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(120) NOT NULL,
    "Type" character varying(20) NOT NULL,
    "IsActive" boolean NOT NULL DEFAULT TRUE,
    CONSTRAINT "PK_institutions" PRIMARY KEY ("Id")
);

CREATE TABLE investment_goals (
    "Id" uuid NOT NULL,
    "UserId" uuid NOT NULL,
    "TargetAmount" numeric(18,2) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_investment_goals" PRIMARY KEY ("Id")
);

CREATE TABLE investment_positions (
    "Id" uuid NOT NULL,
    "UserId" uuid NOT NULL,
    "Type" text NOT NULL,
    "Asset" character varying(200) NOT NULL,
    "Quantity" numeric(18,6) NOT NULL,
    "AvgPrice" numeric(18,2) NOT NULL,
    "OpenedAt" date NOT NULL,
    "Account" character varying(120) NOT NULL,
    "Category" character varying(80) NOT NULL,
    "Note" character varying(400),
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_investment_positions" PRIMARY KEY ("Id")
);

CREATE TABLE notification_settings (
    "Id" uuid NOT NULL,
    "IncomeUpcomingEnabled" boolean NOT NULL,
    "IncomeDaysBefore" integer NOT NULL,
    "ExpenseUpcomingEnabled" boolean NOT NULL,
    "ExpenseDaysBefore" integer NOT NULL,
    "ExpenseOverdueEnabled" boolean NOT NULL,
    "CardCloseSoonEnabled" boolean NOT NULL,
    "CardCloseDaysBefore" integer NOT NULL,
    "CardCloseDayEnabled" boolean NOT NULL,
    "MonthCloseEnabled" boolean NOT NULL,
    "MonthSummaryEnabled" boolean NOT NULL,
    "GoalBelowExpectedEnabled" boolean NOT NULL,
    "GoalCompletedEnabled" boolean NOT NULL,
    "GoalInactivityEnabled" boolean NOT NULL,
    "GoalInactivityDays" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_notification_settings" PRIMARY KEY ("Id")
);

CREATE TABLE payment_methods (
    "Id" integer NOT NULL,
    "Name" character varying(100) NOT NULL,
    "IsActive" boolean NOT NULL DEFAULT TRUE,
    CONSTRAINT "PK_payment_methods" PRIMARY KEY ("Id")
);

CREATE TABLE user_notifications (
    "Id" uuid NOT NULL,
    "UserId" uuid NOT NULL,
    "PlanId" uuid,
    "InstallmentId" uuid,
    "MoneyType" text,
    "Kind" text NOT NULL,
    "ReferenceKey" character varying(160) NOT NULL,
    "Title" character varying(160) NOT NULL,
    "Message" character varying(500) NOT NULL,
    "DueDate" date,
    "CreatedAt" timestamp with time zone NOT NULL,
    "ReadAt" timestamp with time zone,
    CONSTRAINT "PK_user_notifications" PRIMARY KEY ("Id")
);

CREATE TABLE user_onboarding (
    "Id" uuid NOT NULL,
    "UserId" uuid NOT NULL,
    "Step" integer NOT NULL,
    "Completed" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_user_onboarding" PRIMARY KEY ("Id")
);

CREATE TABLE user_profiles (
    "Id" uuid NOT NULL,
    "UserId" uuid NOT NULL,
    "FullName" character varying(200) NOT NULL,
    "Document" character varying(50) NOT NULL,
    "Phone" character varying(30) NOT NULL,
    "BirthDate" timestamp with time zone,
    "AvatarUrl" character varying(400),
    "City" character varying(120),
    "State" character varying(80),
    "Country" character varying(120),
    "Language" character varying(10),
    "Currency" character varying(10),
    "NotifyUpcomingEnabled" boolean NOT NULL,
    "NotifyOverdueEnabled" boolean NOT NULL,
    "NotifyEmailEnabled" boolean NOT NULL,
    "NotifyInAppEnabled" boolean NOT NULL,
    "NotifyDaysBeforeDue" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_user_profiles" PRIMARY KEY ("Id")
);

CREATE TABLE users (
    "Id" uuid NOT NULL,
    "Name" character varying(200) NOT NULL,
    "Email" character varying(200) NOT NULL,
    "PasswordHash" character varying(500) NOT NULL,
    "Role" character varying(30) NOT NULL DEFAULT 'Basic',
    "IsActive" boolean NOT NULL DEFAULT TRUE,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    "LastLoginAt" timestamp with time zone,
    "FailedLoginAttempts" integer NOT NULL DEFAULT 0,
    "LockoutUntil" timestamp with time zone,
    CONSTRAINT "PK_users" PRIMARY KEY ("Id")
);

CREATE TABLE cards (
    "Id" uuid NOT NULL,
    "UserId" uuid NOT NULL,
    "BrandId" integer NOT NULL,
    "Bank" character varying(120),
    "CreditLimit" numeric(14,2) NOT NULL,
    "StatementCloseDay" integer NOT NULL,
    "DueDay" integer NOT NULL,
    "HolderName" character varying(200) NOT NULL,
    "Nickname" character varying(200) NOT NULL,
    "Last4" character varying(4) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_cards" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_cards_card_brands_BrandId" FOREIGN KEY ("BrandId") REFERENCES card_brands ("Id") ON DELETE RESTRICT
);

CREATE TABLE investment_movements (
    "Id" uuid NOT NULL,
    "PositionId" uuid NOT NULL,
    "Type" text NOT NULL,
    "Quantity" numeric(18,6) NOT NULL,
    "Price" numeric(18,2) NOT NULL,
    "Date" date NOT NULL,
    "Note" character varying(400),
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_investment_movements" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_investment_movements_investment_positions_PositionId" FOREIGN KEY ("PositionId") REFERENCES investment_positions ("Id") ON DELETE CASCADE
);

CREATE TABLE audit_logs (
    "Id" uuid NOT NULL,
    "UserId" uuid,
    "Action" character varying(80) NOT NULL,
    "Entity" character varying(80) NOT NULL,
    "EntityId" character varying(200),
    "IpAddress" character varying(64),
    "UserAgent" character varying(400),
    "Metadata" text,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_audit_logs" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_audit_logs_users_UserId" FOREIGN KEY ("UserId") REFERENCES users ("Id") ON DELETE SET NULL
);

CREATE TABLE refresh_tokens (
    "Id" uuid NOT NULL,
    "UserId" uuid NOT NULL,
    "TokenHash" character varying(200) NOT NULL,
    "ExpiresAt" timestamp with time zone NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "RevokedAt" timestamp with time zone,
    "ReplacedByTokenHash" character varying(200),
    CONSTRAINT "PK_refresh_tokens" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_refresh_tokens_users_UserId" FOREIGN KEY ("UserId") REFERENCES users ("Id") ON DELETE CASCADE
);

CREATE TABLE password_reset_tokens (
    "Id" uuid NOT NULL,
    "UserId" uuid NOT NULL,
    "TokenHash" character varying(200) NOT NULL,
    "ExpiresAt" timestamp with time zone NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UsedAt" timestamp with time zone,
    CONSTRAINT "PK_password_reset_tokens" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_password_reset_tokens_users_UserId" FOREIGN KEY ("UserId") REFERENCES users ("Id") ON DELETE CASCADE
);

CREATE TABLE money_plans (
    "Id" uuid NOT NULL,
    "UserId" uuid NOT NULL,
    "Type" text NOT NULL,
    "Title" character varying(120) NOT NULL,
    "CategoryId" uuid,
    "CardId" uuid,
    "Amount" numeric(14,2) NOT NULL,
    "Schedule" text NOT NULL,
    "Frequency" text,
    "InstallmentsCount" integer,
    "DefaultPaymentMethodId" integer,
    "StartDate" date NOT NULL,
    "Status" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_money_plans" PRIMARY KEY ("Id"),
    CONSTRAINT ck_money_plans_schedule CHECK (("Schedule" = 'OneTime' AND "InstallmentsCount" = 1 AND "Frequency" IS NULL) OR ("Schedule" = 'Installments' AND "InstallmentsCount" >= 2 AND "Frequency" IS NULL) OR ("Schedule" = 'Recurring' AND "InstallmentsCount" IS NULL AND "Frequency" IS NOT NULL)),
    CONSTRAINT "FK_money_plans_cards_CardId" FOREIGN KEY ("CardId") REFERENCES cards ("Id") ON DELETE SET NULL,
    CONSTRAINT "FK_money_plans_categories_CategoryId" FOREIGN KEY ("CategoryId") REFERENCES categories ("Id") ON DELETE SET NULL
);

CREATE TABLE money_installments (
    "Id" uuid NOT NULL,
    "PlanId" uuid NOT NULL,
    "UserId" uuid NOT NULL,
    "InstallmentNo" integer NOT NULL,
    "DueDate" date NOT NULL,
    "OriginalDueDate" date,
    "Amount" numeric(14,2) NOT NULL,
    "Status" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_money_installments" PRIMARY KEY ("Id"),
    CONSTRAINT ck_installment_amount_positive CHECK ("Amount" > 0),
    CONSTRAINT ck_installment_no_positive CHECK ("InstallmentNo" >= 1),
    CONSTRAINT "FK_money_installments_money_plans_PlanId" FOREIGN KEY ("PlanId") REFERENCES money_plans ("Id") ON DELETE CASCADE
);

CREATE TABLE money_payments (
    "Id" uuid NOT NULL,
    "InstallmentId" uuid NOT NULL,
    "UserId" uuid NOT NULL,
    "PaidAt" timestamp with time zone NOT NULL,
    "PaidAmount" numeric(14,2) NOT NULL,
    "MethodId" integer,
    "Note" character varying(200),
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_money_payments" PRIMARY KEY ("Id"),
    CONSTRAINT ck_payment_amount_positive CHECK ("PaidAmount" > 0),
    CONSTRAINT "FK_money_payments_money_installments_InstallmentId" FOREIGN KEY ("InstallmentId") REFERENCES money_installments ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_audit_logs_CreatedAt" ON audit_logs ("CreatedAt");

CREATE INDEX "IX_audit_logs_UserId" ON audit_logs ("UserId");

CREATE UNIQUE INDEX "IX_card_brands_Code" ON card_brands ("Code");

CREATE INDEX "IX_cards_BrandId" ON cards ("BrandId");

CREATE UNIQUE INDEX "IX_cards_UserId_Nickname" ON cards ("UserId", "Nickname");

CREATE UNIQUE INDEX "IX_categories_UserId_Name" ON categories ("UserId", "Name");

CREATE INDEX "IX_goal_contributions_GoalId_Date" ON goal_contributions ("GoalId", "Date");

CREATE INDEX "IX_goals_UserId_Status" ON goals ("UserId", "Status");

CREATE INDEX "IX_goals_UserId_Year" ON goals ("UserId", "Year");

CREATE UNIQUE INDEX "IX_institutions_Name_Type" ON institutions ("Name", "Type");

CREATE UNIQUE INDEX "IX_investment_goals_UserId" ON investment_goals ("UserId");

CREATE INDEX "IX_investment_movements_PositionId" ON investment_movements ("PositionId");

CREATE INDEX "IX_investment_positions_UserId_Asset" ON investment_positions ("UserId", "Asset");

CREATE INDEX "IX_money_installments_PlanId_DueDate" ON money_installments ("PlanId", "DueDate");

CREATE UNIQUE INDEX "IX_money_installments_PlanId_InstallmentNo" ON money_installments ("PlanId", "InstallmentNo");

CREATE INDEX "IX_money_installments_UserId_DueDate" ON money_installments ("UserId", "DueDate");

CREATE INDEX "IX_money_payments_InstallmentId" ON money_payments ("InstallmentId");

CREATE INDEX "IX_money_payments_UserId_PaidAt" ON money_payments ("UserId", "PaidAt");

CREATE INDEX "IX_money_plans_CardId" ON money_plans ("CardId");

CREATE INDEX "IX_money_plans_CategoryId" ON money_plans ("CategoryId");

CREATE INDEX "IX_money_plans_UserId" ON money_plans ("UserId");

CREATE UNIQUE INDEX "IX_refresh_tokens_TokenHash" ON refresh_tokens ("TokenHash");

CREATE INDEX "IX_refresh_tokens_UserId" ON refresh_tokens ("UserId");

CREATE UNIQUE INDEX "IX_password_reset_tokens_TokenHash" ON password_reset_tokens ("TokenHash");

CREATE INDEX "IX_password_reset_tokens_UserId" ON password_reset_tokens ("UserId");

CREATE INDEX "IX_user_notifications_UserId_CreatedAt" ON user_notifications ("UserId", "CreatedAt");

CREATE UNIQUE INDEX "IX_user_notifications_UserId_ReferenceKey" ON user_notifications ("UserId", "ReferenceKey");

CREATE UNIQUE INDEX "IX_user_onboarding_UserId" ON user_onboarding ("UserId");

CREATE UNIQUE INDEX "IX_user_profiles_UserId" ON user_profiles ("UserId");

CREATE UNIQUE INDEX "IX_users_Email" ON users ("Email");

