-- Idempotent schema patch script. Keep this file updated as the EF model evolves.

CREATE TABLE IF NOT EXISTS institutions (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(120) NOT NULL,
    "Type" character varying(20) NOT NULL,
    "IsActive" boolean NOT NULL DEFAULT TRUE,
    CONSTRAINT "PK_institutions" PRIMARY KEY ("Id")
);

CREATE UNIQUE INDEX IF NOT EXISTS "IX_institutions_Name_Type"
    ON institutions ("Name", "Type");

CREATE TABLE IF NOT EXISTS accounts (
    "Id" uuid NOT NULL,
    "UserId" uuid NOT NULL,
    "Name" character varying(120) NOT NULL,
    "Type" text NOT NULL,
    "InitialBalance" numeric(14,2) NOT NULL DEFAULT 0,
    "IsActive" boolean NOT NULL DEFAULT TRUE,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_accounts" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_accounts_users_UserId" FOREIGN KEY ("UserId") REFERENCES users ("Id") ON DELETE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS "IX_accounts_UserId_Name"
    ON accounts ("UserId", "Name");

CREATE INDEX IF NOT EXISTS "IX_accounts_UserId_IsActive"
    ON accounts ("UserId", "IsActive");

CREATE TABLE IF NOT EXISTS account_transactions (
    "Id" uuid NOT NULL,
    "AccountId" uuid NOT NULL,
    "UserId" uuid NOT NULL,
    "OccurredAt" timestamp with time zone NOT NULL,
    "Kind" text NOT NULL,
    "Amount" numeric(14,2) NOT NULL,
    "Description" character varying(200) NOT NULL,
    "SourceType" character varying(60),
    "SourceId" uuid,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_account_transactions" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_account_transactions_accounts_AccountId" FOREIGN KEY ("AccountId") REFERENCES accounts ("Id") ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS "IX_account_transactions_AccountId_OccurredAt"
    ON account_transactions ("AccountId", "OccurredAt");

CREATE INDEX IF NOT EXISTS "IX_account_transactions_UserId_OccurredAt"
    ON account_transactions ("UserId", "OccurredAt");

CREATE INDEX IF NOT EXISTS "IX_account_transactions_SourceType_SourceId"
    ON account_transactions ("SourceType", "SourceId");

CREATE TABLE IF NOT EXISTS user_categorization_feedback (
    "Id" uuid NOT NULL,
    "UserId" uuid NOT NULL,
    "Type" text NOT NULL,
    "NormalizedPattern" character varying(160) NOT NULL,
    "CategoryId" uuid NOT NULL,
    "Hits" integer NOT NULL DEFAULT 1,
    "FirstLearnedAt" timestamp with time zone NOT NULL,
    "LastLearnedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_user_categorization_feedback" PRIMARY KEY ("Id")
);

CREATE UNIQUE INDEX IF NOT EXISTS "IX_user_categorization_feedback_UserId_Type_NormalizedPattern"
    ON user_categorization_feedback ("UserId", "Type", "NormalizedPattern");

CREATE INDEX IF NOT EXISTS "IX_user_categorization_feedback_UserId_Type_LastLearnedAt"
    ON user_categorization_feedback ("UserId", "Type", "LastLearnedAt");

CREATE TABLE IF NOT EXISTS user_notifications (
    "Id" uuid NOT NULL,
    "UserId" uuid NOT NULL,
    "PlanId" uuid NULL,
    "InstallmentId" uuid NULL,
    "MoneyType" text NULL,
    "Kind" text NOT NULL,
    "ReferenceKey" character varying(160) NOT NULL,
    "Title" character varying(160) NOT NULL,
    "Message" character varying(500) NOT NULL,
    "PayloadJson" character varying(4000) NULL,
    "DueDate" date NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "ReadAt" timestamp with time zone NULL,
    CONSTRAINT "PK_user_notifications" PRIMARY KEY ("Id")
);

ALTER TABLE IF EXISTS user_notifications
    ADD COLUMN IF NOT EXISTS "PayloadJson" character varying(4000) NULL;

CREATE INDEX IF NOT EXISTS "IX_user_notifications_UserId_CreatedAt"
    ON user_notifications ("UserId", "CreatedAt");

CREATE UNIQUE INDEX IF NOT EXISTS "IX_user_notifications_UserId_ReferenceKey"
    ON user_notifications ("UserId", "ReferenceKey");

CREATE TABLE IF NOT EXISTS user_feature_overrides (
    "Id" uuid NOT NULL,
    "UserId" uuid NOT NULL,
    "FeatureKey" character varying(120) NOT NULL,
    "IsEnabled" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_user_feature_overrides" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_user_feature_overrides_users_UserId" FOREIGN KEY ("UserId") REFERENCES users ("Id") ON DELETE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS "IX_user_feature_overrides_UserId_FeatureKey"
    ON user_feature_overrides ("UserId", "FeatureKey");

CREATE TABLE IF NOT EXISTS robot_execution_logs (
    "Id" uuid NOT NULL,
    "RobotName" character varying(80) NOT NULL,
    "StartedAt" timestamp with time zone NOT NULL,
    "FinishedAt" timestamp with time zone NOT NULL,
    "DurationMs" bigint NOT NULL DEFAULT 0,
    "CorrelationId" character varying(64) NOT NULL DEFAULT '',
    "HostName" character varying(120) NOT NULL DEFAULT 'unknown',
    "TriggeredByUserId" uuid NULL,
    "Success" boolean NOT NULL,
    "ProcessedCount" integer NOT NULL,
    "EmailsAttempted" integer NOT NULL DEFAULT 0,
    "EmailsSent" integer NOT NULL DEFAULT 0,
    "EmailsFailed" integer NOT NULL DEFAULT 0,
    "ZeroItemsReasonCode" character varying(100) NULL,
    "WasSkipped" boolean NOT NULL DEFAULT FALSE,
    "SkipReason" character varying(200) NULL,
    "Error" character varying(2000) NULL,
    CONSTRAINT "PK_robot_execution_logs" PRIMARY KEY ("Id")
);

CREATE INDEX IF NOT EXISTS "IX_robot_execution_logs_RobotName_StartedAt"
    ON robot_execution_logs ("RobotName", "StartedAt");

CREATE TABLE IF NOT EXISTS notification_settings (
    "Id" uuid NOT NULL,
    "IncomeUpcomingEnabled" boolean NOT NULL DEFAULT TRUE,
    "IncomeDaysBefore" integer NOT NULL DEFAULT 2,
    "ExpenseUpcomingEnabled" boolean NOT NULL DEFAULT TRUE,
    "ExpenseDaysBefore" integer NOT NULL DEFAULT 2,
    "ExpenseOverdueEnabled" boolean NOT NULL DEFAULT TRUE,
    "CardCloseSoonEnabled" boolean NOT NULL DEFAULT TRUE,
    "CardCloseDaysBefore" integer NOT NULL DEFAULT 2,
    "CardCloseDayEnabled" boolean NOT NULL DEFAULT TRUE,
    "MonthCloseEnabled" boolean NOT NULL DEFAULT TRUE,
    "MonthSummaryEnabled" boolean NOT NULL DEFAULT TRUE,
    "GoalBelowExpectedEnabled" boolean NOT NULL DEFAULT TRUE,
    "GoalCompletedEnabled" boolean NOT NULL DEFAULT TRUE,
    "GoalInactivityEnabled" boolean NOT NULL DEFAULT TRUE,
    "GoalInactivityDays" integer NOT NULL DEFAULT 30,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT NOW(),
    "UpdatedAt" timestamp with time zone NOT NULL DEFAULT NOW(),
    CONSTRAINT "PK_notification_settings" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS robot_settings (
    "Id" uuid NOT NULL,
    "Enabled" boolean NOT NULL DEFAULT TRUE,
    "DailyRunTimeUtc" character varying(5) NOT NULL DEFAULT '08:00',
    "UpdatedAt" timestamp with time zone NOT NULL DEFAULT NOW(),
    CONSTRAINT "PK_robot_settings" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS investment_allocation_targets (
    "Id" uuid NOT NULL,
    "UserId" uuid NOT NULL,
    "Rf" numeric(5,2) NOT NULL,
    "Acoes" numeric(5,2) NOT NULL,
    "Fundos" numeric(5,2) NOT NULL,
    "Cripto" numeric(5,2) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_investment_allocation_targets" PRIMARY KEY ("Id")
);

CREATE UNIQUE INDEX IF NOT EXISTS "IX_investment_allocation_targets_UserId"
    ON investment_allocation_targets ("UserId");

CREATE TABLE IF NOT EXISTS password_reset_tokens (
    "Id" uuid NOT NULL,
    "UserId" uuid NOT NULL,
    "TokenHash" character varying(200) NOT NULL,
    "ExpiresAt" timestamp with time zone NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UsedAt" timestamp with time zone NULL,
    CONSTRAINT "PK_password_reset_tokens" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_password_reset_tokens_users_UserId" FOREIGN KEY ("UserId") REFERENCES users ("Id") ON DELETE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS "IX_password_reset_tokens_TokenHash"
    ON password_reset_tokens ("TokenHash");

CREATE INDEX IF NOT EXISTS "IX_password_reset_tokens_UserId"
    ON password_reset_tokens ("UserId");

DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM information_schema.tables
        WHERE table_schema = 'public' AND table_name = 'robot_execution_logs'
    ) THEN
        ALTER TABLE robot_execution_logs ADD COLUMN IF NOT EXISTS "EmailsAttempted" integer NOT NULL DEFAULT 0;
        ALTER TABLE robot_execution_logs ADD COLUMN IF NOT EXISTS "EmailsSent" integer NOT NULL DEFAULT 0;
        ALTER TABLE robot_execution_logs ADD COLUMN IF NOT EXISTS "EmailsFailed" integer NOT NULL DEFAULT 0;
        ALTER TABLE robot_execution_logs ADD COLUMN IF NOT EXISTS "ZeroItemsReasonCode" character varying(100);
        ALTER TABLE robot_execution_logs ADD COLUMN IF NOT EXISTS "DurationMs" bigint NOT NULL DEFAULT 0;
        ALTER TABLE robot_execution_logs ADD COLUMN IF NOT EXISTS "CorrelationId" character varying(64) NOT NULL DEFAULT '';
        ALTER TABLE robot_execution_logs ADD COLUMN IF NOT EXISTS "HostName" character varying(120) NOT NULL DEFAULT 'unknown';
        ALTER TABLE robot_execution_logs ADD COLUMN IF NOT EXISTS "TriggeredByUserId" uuid;
        ALTER TABLE robot_execution_logs ADD COLUMN IF NOT EXISTS "WasSkipped" boolean NOT NULL DEFAULT FALSE;
        ALTER TABLE robot_execution_logs ADD COLUMN IF NOT EXISTS "SkipReason" character varying(200);
    END IF;

    IF EXISTS (
        SELECT 1
        FROM information_schema.tables
        WHERE table_schema = 'public' AND table_name = 'robot_settings'
    ) THEN
        ALTER TABLE robot_settings ADD COLUMN IF NOT EXISTS "Enabled" boolean NOT NULL DEFAULT TRUE;
        ALTER TABLE robot_settings ADD COLUMN IF NOT EXISTS "DailyRunTimeUtc" character varying(5) NOT NULL DEFAULT '08:00';
        ALTER TABLE robot_settings ADD COLUMN IF NOT EXISTS "UpdatedAt" timestamp with time zone NOT NULL DEFAULT NOW();
    END IF;

    IF EXISTS (
        SELECT 1
        FROM information_schema.tables
        WHERE table_schema = 'public' AND table_name = 'money_installments'
    ) THEN
        ALTER TABLE money_installments ADD COLUMN IF NOT EXISTS "StatementYear" integer;
        ALTER TABLE money_installments ADD COLUMN IF NOT EXISTS "StatementMonth" integer;
        ALTER TABLE money_installments ADD COLUMN IF NOT EXISTS "StatementCloseDate" date;
        ALTER TABLE money_installments ADD COLUMN IF NOT EXISTS "StatementDueDate" date;
    END IF;

    IF EXISTS (
        SELECT 1
        FROM information_schema.tables
        WHERE table_schema = 'public' AND table_name = 'money_payments'
    ) THEN
        ALTER TABLE money_payments ADD COLUMN IF NOT EXISTS "AccountId" uuid;

        IF NOT EXISTS (
            SELECT 1
            FROM pg_constraint
            WHERE conname = 'FK_money_payments_accounts_AccountId'
        ) THEN
            ALTER TABLE money_payments
            ADD CONSTRAINT "FK_money_payments_accounts_AccountId"
            FOREIGN KEY ("AccountId") REFERENCES accounts ("Id") ON DELETE SET NULL;
        END IF;
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS "IX_money_payments_AccountId"
    ON money_payments ("AccountId");

CREATE TABLE IF NOT EXISTS loan_contracts (
    "Id" uuid NOT NULL,
    "UserId" uuid NOT NULL,
    "Title" character varying(160) NOT NULL,
    "PrincipalAmount" numeric(14,2) NOT NULL,
    "AnnualInterestRate" numeric(7,4) NOT NULL,
    "TermMonths" integer NOT NULL,
    "AmortizationType" text NOT NULL,
    "StartDate" date NOT NULL,
    "PaymentDay" integer NOT NULL,
    "MonthlyPayment" numeric(14,2) NOT NULL,
    "TotalCost" numeric(14,2) NOT NULL,
    "TotalInterest" numeric(14,2) NOT NULL,
    "Status" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_loan_contracts" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_loan_contracts_users_UserId" FOREIGN KEY ("UserId") REFERENCES users ("Id") ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS "IX_loan_contracts_UserId_CreatedAt"
    ON loan_contracts ("UserId", "CreatedAt");

CREATE INDEX IF NOT EXISTS "IX_loan_contracts_UserId_Status"
    ON loan_contracts ("UserId", "Status");

CREATE TABLE IF NOT EXISTS loan_installments (
    "Id" uuid NOT NULL,
    "ContractId" uuid NOT NULL,
    "UserId" uuid NOT NULL,
    "InstallmentNo" integer NOT NULL,
    "DueDate" date NOT NULL,
    "BeginningBalance" numeric(14,2) NOT NULL,
    "PrincipalAmount" numeric(14,2) NOT NULL,
    "InterestAmount" numeric(14,2) NOT NULL,
    "TotalAmount" numeric(14,2) NOT NULL,
    "EndingBalance" numeric(14,2) NOT NULL,
    "Status" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    "PaidAt" timestamp with time zone NULL,
    CONSTRAINT "PK_loan_installments" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_loan_installments_loan_contracts_ContractId" FOREIGN KEY ("ContractId") REFERENCES loan_contracts ("Id") ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS "IX_loan_installments_UserId_DueDate"
    ON loan_installments ("UserId", "DueDate");

CREATE UNIQUE INDEX IF NOT EXISTS "IX_loan_installments_ContractId_InstallmentNo"
    ON loan_installments ("ContractId", "InstallmentNo");

CREATE TABLE IF NOT EXISTS monthly_financial_snapshots (
    "Id" uuid NOT NULL,
    "UserId" uuid NOT NULL,
    "Year" integer NOT NULL,
    "Month" integer NOT NULL,
    "SnapshotLabel" character varying(7) NOT NULL,
    "RealAvailableBalance" numeric(14,2) NOT NULL,
    "ProjectedBalance" numeric(14,2) NOT NULL,
    "PendingExpenses" numeric(14,2) NOT NULL,
    "PendingIncomes" numeric(14,2) NOT NULL,
    "TotalDebt" numeric(14,2) NOT NULL,
    "NetWorth" numeric(14,2) NOT NULL,
    "RiskScore" integer NOT NULL,
    "RiskClassification" character varying(40) NOT NULL,
    "PrimaryInsight" character varying(500) NOT NULL,
    "RecommendationsJson" character varying(4000) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_monthly_financial_snapshots" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_monthly_financial_snapshots_users_UserId" FOREIGN KEY ("UserId") REFERENCES users ("Id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS user_subscriptions (
    id uuid PRIMARY KEY,
    user_id uuid NOT NULL UNIQUE,
    plan_code varchar(32) NOT NULL,
    role_granted integer NOT NULL,
    billing_cycle integer NOT NULL,
    status integer NOT NULL,
    price_amount numeric(14,2) NOT NULL,
    currency varchar(8) NOT NULL,
    auto_renew boolean NOT NULL DEFAULT TRUE,
    started_at timestamp without time zone NOT NULL,
    renews_at timestamp without time zone NOT NULL,
    cancelled_at timestamp without time zone NULL,
    updated_at timestamp without time zone NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS "IX_monthly_financial_snapshots_UserId_Year_Month"
    ON monthly_financial_snapshots ("UserId", "Year", "Month");

DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM information_schema.tables
        WHERE table_schema = 'public' AND table_name = 'user_profiles'
    ) THEN
        ALTER TABLE user_profiles ADD COLUMN IF NOT EXISTS "NotifyUpcomingEnabled" boolean NOT NULL DEFAULT TRUE;
        ALTER TABLE user_profiles ADD COLUMN IF NOT EXISTS "NotifyOverdueEnabled" boolean NOT NULL DEFAULT TRUE;
        ALTER TABLE user_profiles ADD COLUMN IF NOT EXISTS "NotifyEmailEnabled" boolean NOT NULL DEFAULT FALSE;
        ALTER TABLE user_profiles ADD COLUMN IF NOT EXISTS "NotifyInAppEnabled" boolean NOT NULL DEFAULT TRUE;
        ALTER TABLE user_profiles ADD COLUMN IF NOT EXISTS "NotifyDaysBeforeDue" integer NOT NULL DEFAULT 3;
        ALTER TABLE user_profiles ADD COLUMN IF NOT EXISTS "FinancialGoal" character varying(80);
        ALTER TABLE user_profiles ADD COLUMN IF NOT EXISTS "CarryOverDay" integer NOT NULL DEFAULT 1;
        ALTER TABLE user_profiles ADD COLUMN IF NOT EXISTS "IntelligenceMode" character varying(1) NOT NULL DEFAULT 'B';
    END IF;
END $$;

DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM information_schema.tables
        WHERE table_schema = 'public' AND table_name = 'users'
    ) THEN
        ALTER TABLE users ADD COLUMN IF NOT EXISTS "Role" character varying(30) NOT NULL DEFAULT 'Basic';
    END IF;
END $$;
